### ISSUE TITLE
IPFS files can't be added

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1866] opened 2023-01-24 09:56 UTC
During publish, whenever I input a CID I get:

<img width="909" alt="Screenshot 2023-01-24 at 09 55 53" src="https://user-images.githubusercontent.com/90316/214261739-b40a6d8b-aa49-490a-b26d-632b88462af1.png">

So not possible to publish IPFS files right now through our UI.

Using this CID for testing: `QmTXDxopoBXtqxwtnxDPfC77g46AJtL3b2H8u7zAcveA8S`

**Comment by bogdanfazakas** [comment] 2023-01-24 10:04
this seems to be fixed by this pr #1794

**Comment by EnzoVezzaro** [comment] 2023-01-24 15:56
On main branch there's an issue, which has been solve in #1794 (we already talked about it and fixed it here), related to the CID being treated as URL. 

<img width="928" alt="Screenshot 2023-01-24 at 11 50 48" src="https://user-images.githubusercontent.com/13741335/214341424-6506d51b-bf73-4ce5-b82d-b2667ad9cb31.png">
<img width="938" alt="Screenshot 2023-01-24 at 11 50 50" src="https://user-images.githubusercontent.com/13741335/214341427-dc1d54ae-bccf-4c2a-80c4-e1b57a35cbee.png">

This issue has been fix on this [commit](https://github.com/oceanprotocol/market/pull/1794/commits/faafba5a8abce4685e737d980a5ce49345a21aa1).

The issue described it's not caused by the data being sent, on the network you can see what's being sent to provider (need fix in commit):

`{
  "type": "ipfs",
  "hash": "bafkreiaxfszya2qz3vdgdw3da3rbfsvnlwez2x5wjaf66uqheeo22nc3fu",
  "checksum": false
}`

On the debug in main you still see URL as parameter, but it just UI, on the back is handle as HASH. This preview debug issue has also been fixed in #1794 
<img width="277" alt="Screenshot 2023-01-24 at 11 49 15" src="https://user-images.githubusercontent.com/13741335/214340988-970e3d7a-8489-45bd-b1fe-51bbfe3070ee.png">

I think that @kremalicious 's issue needs more investigation, as I wasn't able to reproduce the "Type error" issue.

**Closed** 2023-01-27 12:30 UTC
Labels: Type: Bug, Priority: High
