### ISSUE TITLE
Whitelisting and Blacklisting of Assets by Publishers

### ISSUE THREAD

**Issue by srikanthkaja31** [oceanprotocol/market#513] opened 2021-04-14 14:33 UTC
**Describe the solution you'd like**

As a data seller, I would like to whitelist or blacklist the assets based on wallet addresses with a default mechanism to have anyone to consume the asset so that I can align with data protection and anti trust regulations. 

Scenario to be as below :

Default is Allow All consumption
Whitelist A -> No other wallet except A can consume the asset.
Blacklist A -> All wallets except A can consume the asset.

**Additional context**

To consider the changes as part of DDO so Data Publishers can whitelist/blacklist as part of "Edit Metadata" option.
Provider changes to be included so backend calls for consumption are also in sync.

**Comment by alexcos20** [comment] 2021-04-15 07:19
duplicate of https://github.com/oceanprotocol/multi-repo-issue/issues/76 for now, let's take it there

**Closed by alexcos20** 2021-04-15 07:19 UTC
Labels: enhancement
