### ISSUE TITLE
timeout for data set is not respected on repeated order (sometimes, it's random)

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#569] opened 2021-04-28 13:27 UTC
Not entirely sure about this one, just ran into that on Polygon. After starting a compute job on a dataset with a timeout, starting another compute job will buy dataset datatoken again.

1. go to `did:op:76E031A63e4dAB370Ae25b1A93A997e79e084f6f` on Polygon
2. buy compute job
3. reload page to be sure after success, then start another compute job
4. dataset datatoken is bought

Probably should be first replicated on Rinkeby to see if that's a chain-specific problem

### Expectation

When within the timeout after the last buy, no additional datatoken order should happen. Might turn out to be like that, and I just ran into some weird combination because I'm also publisher of all assets being used in my test.

**Comment by KatunaNorbert** [comment] 2021-04-29 09:42
I tested it on Rinkeby but couldn't reproduce it

**Comment by DimitarSD** [comment] 2021-05-03 13:28
I tested it on Polygon, but I didn't manage to reproduce it either. Although, I experienced some other strange behaviors that I'm currently testing. They might have a connection...

**Comment by bogdanfazakas** [comment] 2021-05-17 12:47
As i see this issue is related to #583 , the root problem seems to be the cached values for previous orders. In my tests never bumped into it using the live preview of this PR #588 so it looks like that PR will also close this issue.

**Comment by kremalicious** [comment] 2021-05-17 14:16
Adding to the root problem, in my tests I found that Polygon is simply too fast. Because transactions are finished faster than the subgraph can update its records, so I'm pretty sure even without any GraphQL caching at all we will run into edge cases where the subgraph is not updated yet for some seconds. Never had this problem outside of Polygon though

**Closed** 2021-05-25 09:30 UTC
Labels: bug
