### ISSUE TITLE
Visibility of datasets across marketplaces for publishers (and filters for market providers)

### ISSUE THREAD

**Issue by kaimeinke** [oceanprotocol/market#454] opened 2021-03-24 17:31 UTC
User story:
1. As a publisher I would like to see my asset listed on as many marketplaces as possible to drive sales and interactions with it. 
2. As a market provider I would like to have the highest number of quality datasets as possible to show that all relevant data can be found at my market and I can drive traffic and additional publications through my market.
3. As as market provider I would like to control what kind of assets / which assets are visible on my market. I need to filter from the noise / market segments and I need to take care of datasets that violate terms/restrictions that apply in my region (purgatory).

**Describe the solution you'd like**
I see multiple options here:
1. All markets can be open to all assets that have been published on all chains by default and auto-discover and list them. This can lead to A LOT of noise if this gets the traction we expect in the future.
2. All markets have an option to manually discover new sets (triggered by the admin) and then can be listed selectively by the market provider in a comfortable way (admin interface)
3. All markets only know the datasets they have been created, BUT datasets DIDs can be imported manually in order to get listed on the marketplace. This would require the publisher of the dataset to get into contact with the market provider or the other way arround, but it could be handled as a whitelist or reverse-purgatory.
4. Additional idea would be some kind of global purgatory to quickly get rid of scams, so the original Ocean Market Purgatory would automatically / by default important and used by all markets until you explicitly disable it.

I see Option 2 and 3 as the most comfortable for market providers and I guess 3 would be the most easy one to get things going. 

I actually envision high quality datasets, like stocks, that nearly every marketplace will want to have in the future. This could also be a great place to handle IDOs. You start on one marketplace of origin, do an IDO, and then you move on and open this to the broader public. This will enable real competition between marketplaces to rally for the good publishers.

This would counter early fragmentation of markets in which some which become irrelevant and it would be a shame if the valuable datasets associated with these marketplaces would be lost.

I think this will be a highly valuable feature to drive adoption and really worth the investment especially in its easiest implementation. It will be relevant for the first market fork we are thinking about.

Taken from today Town Hall Meeting as discussed with @trentmc

**Comment by kremalicious** [comment] 2021-03-26 13:15
yup, we agree, thanks for the input! https://github.com/oceanprotocol/multi-repo-issue/issues/67

The current vision is that the `market` will be transformed into an interface spanning multiple chains in some way, where assets from different chains/networks appear alongside each other. We'll get to defining all the details in Q2

**Comment by kaimeinke** [comment] 2021-03-26 13:30
Thanks for the quick reply on this one Matthias. 

Please not that a first implementation as "visible across markets on the same network" would already have a great impact. Would be wonderful to have this as an MVP in one or another way.

Kai

**Comment by trentmc** [comment] 2021-04-08 06:56
> "visible across markets on the same network" would already have a great impact. 

Actually, Ocean already supports this; we put it in by design in v3 for network effects reasons / to prevent silos by marketplaces. 

I'll elaborate: right now when an asset gets published in _any_ market, the asset and its metadata goes on chain, and any market will see it and show it (if the market chooses). It's easy to do since all the data assets come from a single on-chain datatoken factory (DTFactory.sol). 

As for visibility across >1 networks, that's already in a different issue, as Matthias pointed out (multirepo 67).

Closing this issue as it's already done:) Kai -- if you believe there is something else that this issue identified, that's outside the scope of what's already done in V3 and what's in multi repo 67, please comment.

**Closed by trentmc** 2021-04-08 06:56 UTC
Labels: enhancement

**Comment by kaimeinke** [comment] 2021-04-08 21:38
Absolutely the answers we were looking for. Thank you!
