### ISSUE TITLE
Giving build error opcquery

### ISSUE THREAD

**Issue by insidetry** [oceanprotocol/market#1589] opened 2022-07-10 16:53 UTC
![Screenshot_20220710-221155_cropped](https://user-images.githubusercontent.com/54780129/178154245-1107de12-3ab1-4680-b808-b8da49e26756.png)

**Comment by jamiehewitt15** [comment] 2022-07-11 08:15
Please make sure you are following all of the steps for running that market. You can find instructions [here](https://github.com/oceanprotocol/market/). The best place to get support is the `#dev-support` channel in our Discord

Closing this issue as it is a duplicate of: https://github.com/oceanprotocol/market/issues/1535

**Closed by jamiehewitt15** 2022-07-11 08:15 UTC
