### ISSUE TITLE
Free price data asset not being displayed on Firefox

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1241] opened 2022-03-23 11:33 UTC
Found a bug displaying an asset in Firefox

Describe the bug
After creating a free price dataset on Rinkeby, Firefox doesn't show the information due to an error. In the console I can see:
TypeError: e.baseToken is undefined
    NextJS 96
framework-bb5c596eafb42b22.js:1:82745
    NextJS 98
TypeError: e.baseToken is undefined
    NextJS 96
main-914fbfab4f90b52f.js:1:11478

A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred main-914fbfab4f90b52f.js:1:11495
GEThttps://v4.market.oceanprotocol.com/favicon.ico
In other browsers like Brave or Chrome it works correctly.

To Reproduce
Go to URL https://v4.market.oceanprotocol.com/asset/did:op:7e798ca9328cc6787ca3e3c07385b2736b9c191dbae99ff9097403e551118893 in Firefox

Expected behavior
Display correctly the information
Desktop:
OS: MacOS 12.3
Browser Firefox
Version 98.0.1
<img width="1438" alt="Screenshot 2022-03-17 at 23 45 37" src="https://user-images.githubusercontent.com/84312885/159690187-182282c1-2e80-4351-916a-a53e7c44808d.png">

**Comment by kremalicious** [comment] 2022-03-23 13:02
duplicate of #1213

**Closed by kremalicious** 2022-03-23 13:02 UTC
Labels: Type: Bug
