### ISSUE TITLE
Fileinfo replacement

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/market#348] opened 2021-01-27 19:15 UTC
Market should use ocean.provider.fileinfo  (https://github.com/oceanprotocol/ocean.js/blob/main/src/provider/Provider.ts#L81) instead of using it's own endpoint
(https://github.com/oceanprotocol/market/blob/main/src/utils/index.ts#L45)

**Comment by mihaisc** [comment] 2021-01-28 09:41
Once this is done we should remove this endpoint `https://fileinfo.oceanprotocol.com`

**Comment by kremalicious** [comment] 2021-01-28 11:00
duplicate of #318

**Closed by kremalicious** 2021-01-28 11:00 UTC
Labels: bug, prio:high
