### ISSUE TITLE
Download Option does not trigger on Rinkeby

### ISSUE THREAD

**Issue by kaimeinke** [oceanprotocol/market#556] opened 2021-04-25 18:24 UTC
This dataset seems to be broken, or the download function of the market is. Can be reproduced several times.

https://market.oceanprotocol.com/asset/did:op:08A814050DBC4DA746B3b608FaC1C72d13d01f4C

After buying the download never triggers nor does the market ask for a signature before download.

The download does never trigger for this one. Something seems to be off here:

![image](https://user-images.githubusercontent.com/59994024/116004683-1eb21780-a604-11eb-9ac9-cd8fa1bd59d2.png)

**Comment by etcpwd1960** [comment] 2021-04-25 18:41
The data set is 100MB in size and the data is formatted key=value in csv. The file was published to both a pool and also as static pricing. Once published the purchase and block chain process went smooth until the point of clicking the download button. At that point the download starts and then fails as a network error but the transaction still shows as a download. the data was published as a one week time period. When I attempt to download again the application message is that I own it so will not be chaged but I am not asked to sign again nor is the download initiated.

**Comment by mihaisc** [comment] 2021-04-27 07:31
The problem is with the data source, it times out. On our side we don't properly catch and reflect this error in the UI

**Comment by KatunaNorbert** [comment] 2021-06-09 14:05
This seems to be a problem in ocean.js with throwing the proper error message. The market catches the following error:
![Screenshot 2021-06-09 at 16.49.08 2.png](https://images.zenhubusercontent.com/5ff449b376fe2511ba59495d/10782cd0-8bce-468d-93f9-4f4bf937382c)

**Comment by mihaisc** [comment] 2021-06-17 08:18
Do we have an issue in ocean.js describing this?

**Comment by KatunaNorbert** [comment] 2021-06-17 09:26
I created one: #850

**Comment by jamiehewitt15** [comment] 2021-07-14 10:11
This is closed by: https://github.com/oceanprotocol/ocean.js/pull/898
And: https://github.com/oceanprotocol/market/pull/734

We now show a meaningful error message in this scenario: 
![Screenshot from 2021-07-14 13-08-01](https://user-images.githubusercontent.com/20739535/125604729-7a9ac3c9-51fe-4991-a20a-69dd434068f6.png)

**Closed by jamiehewitt15** 2021-07-14 10:11 UTC
Labels: Type: Bug
