### ISSUE TITLE
app crashes if run with a fresh dep install

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1823] opened 2022-12-07 14:19 UTC
**Describe the bug**
If you start the market with a new fresh dep install, you get `TypeError: Cannot set property Request of #<Object> which has only a getter` while building

**To Reproduce**
1. Go to main brach
2. Run `npm i`
3. Run `npm start`

**Expected behavior**
run normally as expected

**Screenshots**
<img width="1028" alt="Screenshot 2022-12-07 at 09 25 48" src="https://user-images.githubusercontent.com/13741335/206202776-690605b1-b969-48a5-8258-328d0ed1a9c7.png">

**UPDATE**: this was caused by the node version I had installed. You need node 18 as for [package.json](https://github.com/oceanprotocol/market/blob/main/package.json#L122). Closing as it's not a bug

**Comment by jamiehewitt15** [comment] 2022-12-07 14:47
This is caused by using the wrong node.js version, also a duplicate of [this issue](https://github.com/oceanprotocol/market/issues/1811)

**Closed** 2022-12-07 14:49 UTC
Labels: Type: Bug
