### ISSUE TITLE
Allow users specifying token names themselves

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/market#930] opened 2021-10-20 12:13 UTC
<img width="628" alt="Screen Shot 2021-10-20 at 14 11 51" src="https://user-images.githubusercontent.com/2758453/138090207-55a49982-9dfd-4a37-a103-da894e9f5e51.png">

It seems I'm now able to choose my own token name. I'd prefer to define it myself. What is the reason I can't?

**Comment by kremalicious** [comment] 2021-10-20 12:17
duplicate of #61

**Closed by kremalicious** 2021-10-20 12:17 UTC
Labels: Type: Enhancement
