### ISSUE TITLE
Asset published in Market fails to get dispensed

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/market#1725] opened 2022-10-04 11:15 UTC
### The error / how to reproduce

What I did:

1. Published CEXA price feed via Ocean Market, onto Polygon. (Published [here](https://market.oceanprotocol.com/asset/did:op:0dac5eb4965fb2b485181671adbf3a23b0133abf71d2775eda8043e8efc92d19)).

2. Then, tried to consume it via Ocean Market, with a different address. It failed. [This comment has details.](https://github.com/oceanprotocol/market/issues/1725#issuecomment-1268215847).

I also tried to consume it via [this ocean.py README](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/predict-eth.md), with a different address than the publishing one. It failed too. Digging into it...

It appears that by default, the dispenser contract, [`allowedSwapper`](https://github.com/oceanprotocol/contracts/blob/722f6cb91ec2a3c5966b919888b2633601e6ecab/contracts/pools/dispenser/Dispenser.sol#L25) gets set to a nonzero address (not 0x00...). 

Which meant that *only* the publishing account can dispense tokens, unless it's changed via [`setAllowedSwapper()`](https://github.com/oceanprotocol/contracts/blob/722f6cb91ec2a3c5966b919888b2633601e6ecab/contracts/pools/dispenser/Dispenser.sol#L205).

I looked around in Ocean Market to try to change it, such that I could allow anyone to request tokens. Eg next to "change ddo". Such an option did not exist.

But I did find a workaround, in code: via Python, I updated the allowedSwapper to zero address (0x00..) manually. In that setting, it means that anyone can request tokens ([ref](https://github.com/oceanprotocol/contracts/blob/722f6cb91ec2a3c5966b919888b2633601e6ecab/contracts/pools/dispenser/Dispenser.sol#L238)).

### The error, seen again

A user in a data challenge ran into the same issue. See [ocean.py#1161](https://github.com/oceanprotocol/ocean.py/issues/1161)

### Summary

We published a free asset in Ocean Market

A user tried to call dispense(), it didn't work. (Implicitly via a call to ocean_assets::download_file()). It would also fail in any dispense() call from ocean.js, etherscan, or elsewhere.

"Free" assets should be dispense-able. 

The root problem is that: template 2's allowed_swapper != ZERO, which means that no one can call dispense(). 

The challenge is: using template 1 solves the problem, but incurs a second tx and more gas fees (either on publish, or on consume). How do we crack this?

### Candidate approaches, recommendation

**[This comment](https://github.com/oceanprotocol/market/issues/1725#issuecomment-1341398180)** lists several candidate approaches, analyzes them, and makes recommendation on how to proceed. (Hint: it's not "use template 1", we can do better!).

**Comment by mihaisc** [comment] 2022-10-05 10:23
Yes, check my comment, it's failed to download file, and i already created an issue in provider for it. It's not a market issue

**Comment by trentmc** [comment] 2022-10-05 11:00
Summary of observations:
- the issue only happens in Polygon. Not Mumbai, not other networks
- the issue happens when publish from address A, and consume from address B
- the issue happens when consume from address B in Ocean Market, _or_ in ocean.py
- we've only seen issues when publish from Market. The issue does not emerge when publishing from ocean.py READMEs. The issue likely isn't Ocean Market per se. It simply as a different set of calls or params to middleware + smart contracts than ocean.py
- I observed via smart contract queries that `allowedSwapper` was set to a non - 0x00 value by the time Ocean Market publish was done. Matthias reported that the Ocean Market code itself does not set it. Therefore somewhere along the way during publish, it gets set to a non - 0x00 value.
- the issue goes away if you change the `allowedSwapper` to 0x00. This issue's description outlines that more. [Example fix in python](https://github.com/oceanprotocol/market/files/9714987/fix.py.txt)
- I'm guessing that the reported [provider issue](https://github.com/oceanprotocol/provider/issues/544) is a _symptom_ too. Why? because from the last two bullets, `allowedSwapper` value is almost certainly the issue. 

Best way forward, imo: go through the stack of publish from Ocean Market, and find where `allowedSwapper` gets switched to 0x00. Fix that, and we fix this issue (and the provider issue).

(OK, I _really_ have to run now!)

**Comment by mihaisc** [comment] 2022-10-05 11:10
No. please read my comments. 

The behavior is normal for the enterprise template (template id 2) , there is nothing wrong in the market.
I already said in a previous comment what needs to change in the readme to work. 
The provider issue has nothing to do with `allowedSwapper` it's an old recurring issue, most likely something to do with rpc.

**Comment by trentmc** [comment] 2022-10-05 11:22
> No. please read my comments.
> 
> The behavior is normal for the enterprise template (template id 2) , there is nothing wrong in the market. I already said in a previous comment what needs to change in the readme to work. The provider issue has nothing to do with `allowedSwapper` it's an old recurring issue, most likely something to do with rpc.

If that's the case...
-  why was allowedswapper set to nonzero after publish - when I couldn't consume
- and why, when I did change allowedswapper to zero, could I then consume? (Using the readme as is)

And changing the readme doesn't fix the core problem, because the recommended new call couples dispensing tokens (where the issue is) with consuming tokens. Any ocean.py user should be able to get tokens dispensed without having to consume.

**Comment by mihaisc** [comment] 2022-10-05 11:24
> Like I said: The problem likely isn't in market per se. But somewhere in its call stack the allowedswapper got set to nonzero. This is what we need to fix.

Nope, working as intended for the enterprise template. If you really want to get tokens but not order (not sure why) you can use the simple template, not the enterprise one

**Comment by trentmc** [comment] 2022-10-05 11:26
> > Like I said: The problem likely isn't in market per se. But somewhere in its call stack the allowedswapper got set to nonzero. This is what we need to fix.
> 
> Nope, working as intended for the enterprise template. If you really want to get tokens but not order (not sure why) you can use the simple template, not the enterprise one

Why does it default to enterprise template in market then? 

It doesn't make it clear in market that consume would be so restricted.

**Comment by kremalicious** [comment] 2022-10-05 12:16
> Why does it default to enterprise template in market then?

Because everybody touted its advantages, and preventing tax events from occurring in most jurisdiction seems like exactly what we want:
https://github.com/oceanprotocol/contracts/pull/377

The issue here is a typical thing coming up when nobody does actual product design, but everything is just attached as new feature, solving 1 issue but then creating 3 other unintended issues. Like this one here.

Again, you can publish and download via Ocean Market so not sure what to do here. Actual issue then is "Enterprise template does not allow dispensing by default", but that is exactly what it is supposed to do. If this is unwanted, then, well, why do we have all those templates?

We simply can't support all possible combinations and variations of all our stack's features or we would need to have a huge team. We could add an option to choose between the templates but good luck making sure people pick what they actually want, as describing templates (ERC721 & ERC20) and their differences is quite challenging.

Next planned step on market is to at least support downloading with both templates, see #1652

**Comment by trentmc** [comment] 2022-10-05 16:22
The enterprise template was for enterprise markets. Like Daimler.

Ocean Market is not intended to be an enterprise market.

We don't need to support all the templates on Ocean Market. We should simply support the most open one. That's the non enterprise one. 

I propose that's exactly what we do here. Then we won't have any more surprise behavior.
 
Cc @alexcos20

**Comment by trentmc** [comment] 2022-10-05 16:39
The surprise behavior is what I reported at the top of this issue :
- publish on Ocean Market. Free. Expecting open
- Someone else, not in market, goes to request a dispense. And then it doesn't. Because gatekeeper-y enterprise behavior.

That's the surprise behavior. Supposed to be open, but closed in a weird way.

**Comment by mihaisc** [comment] 2022-10-05 17:51
ok got it, so how big of a priority is this change?

**Comment by mihaisc** [comment] 2022-10-05 18:10
That is way too hacky, and would also include extra transactions, i'll just swap templates and ensure compatibility for both.

**Comment by mihaisc** [comment] 2022-10-05 18:37
[PR](https://github.com/oceanprotocol/market/pull/1728) good for testing. Assets published now should work ok with the steps in the readme

**Comment by trentmc** [comment] 2022-12-07 11:50
Note: it appears that this issue has reared its head again. 

Summary:
- we published a free asset in Ocean Market
- user tried to call dispense(), it didn't work. (Implicitly via a call to ocean_assets::download_file()).

Shouldn't "free" assets be dispense-able?

Details in issue [ocean.py#1161](https://github.com/oceanprotocol/ocean.py/issues/1161), see part (2).

**Comment by trentmc** [comment] 2022-12-07 18:30
In [slack](https://oceanprotocol.slack.com/archives/CNDG1849Z/p1670423188730389?thread_ts=1670407882.815929&cid=CNDG1849Z), AlexC expanded on the [PR comment](https://github.com/oceanprotocol/market/pull/1728#discussion_r1022829864) with the reasoning to keep template 2 in Ocean Market:

> there are more advantages for which I prefer to keep enterprise template on market:
> ( 1 tx  (buyFromAndUse) instead of  1 x Buy/dispense + 1 x startOrder)
> 
> 1. reduce costs by 50% (on mainnet, this is important)
> 2. reduce possibility of failure (maybe 1st tx goes through, 2nd fails)
> 3. better UX  (one signature instead of two). Especially when using hw wallets

Yet we still need to solve the issue: "If someone publishes a free asset in ocean market, anyone should be able to call dispense to get the datatoken. (From anywhere: ocean.js, ocean.py, etherscan)". That is, solve _this_ github issue.

And overall, we should ask ourselves:
- do we want users to be able to do a flow at all, vs having gas costs & UX optimized? (But the flow not working)

Let's explore how we can solve the issue. Ideas:
1. switch template to 1
2. if it's a free asset, use template 1 (non-enterprise). And for fixed-price, keep using template 2 (enterprise)
3. if it's a free asset, _do_ the extra transaction to change allowed_swapper to ZERO
4, Maybe more ideas?

I hope we can agree that "does it work at all" >> "UX is better"

**Comment by kremalicious** [comment] 2022-12-08 11:57
we can't have everything, and this can't be solved on the frontend. This is a product/contract issue. If possibility to dispense is more important than everything else we can switch to template 1, if all the user advantages of template 2 are more important to us, we have to keep using template 2. If you want all those features to be on same level then create another template in the contracts with all those features combined, and then make the whole stack switch to this template.

Otherwise we are simply going in circles, expecting the frontend to magically solve all the misconception s of the underlying contracts.

**Comment by jamiehewitt15** [comment] 2023-01-09 16:59
It sounds like this is an issue in the smart contracts rather than the market, so I'd suggest closing this an opening an issue in the contracts repo with regard to writing a new template.

**Comment by trentmc** [comment] 2023-01-10 11:49
> It sounds like this is an issue in the smart contracts rather than the market, so I'd suggest closing this an opening an issue in the contracts repo with regard to writing a new template.

Thanks for the thoughts. 

@alexcos20 ok if I create an issue in contracts repo, and close this one? (I recall that you'd also had ideas for a new template.)

**Comment by mihaisc** [comment] 2023-03-07 11:18
closing since it's not a bug in the market.

**Closed by mihaisc** 2023-03-07 11:18 UTC
Labels: Type: Bug
